config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :persons do
  resources :books
end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :person
   has_attached_file :image
     validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end
	

app/models/person.rb
class Person < ApplicationRecord
	has_many :books ,:dependent => :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

def create
    @person = Person.find(params[:person_id])
    @book = @person.books.create(book_params)
    redirect_to person_path(@person)
  end
 
  def destroy
    @person = Person.find(params[:person_id])
    @book = @person.books.find(params[:id])
    @book.destroy
    redirect_to person_path(@person)
  end
 
  private
    def book_params
      params.require(:book).permit(:name,:pages, :image)
    end

end

app/controllers/persons_controller.rb
class PersonsController < ApplicationController

def new
	  @person = Person.new
  end

 def index
    @persons = Person.all
  end
 
  def show
    @person = Person.find(params[:id])
  end

  def edit
  @person = Person.find(params[:id])
end

def create
  @person = Person.new(person_params)
 
  if @person.save
    redirect_to @person
  else
    render 'new'
  end
end

 
def update
  @person = Person.find(params[:id])
 
  if @person.update(person_params)
    redirect_to @person
  else
    render 'edit'
  end
end

def destroy
  @person = Person.find(params[:id])
  @person.destroy
 
  redirect_to persons_path
end

private
  def person_params
    params.require(:person).permit(:Name, :Age ,:Gender , :Email , :Address)
  end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/persons_helper.rb
module PersonsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>User</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script>
    $(function() {
  $('#pictureInput').on('change', function(event) {
    var files = event.target.files;
    var image = files[0]
    var reader = new FileReader();
    console.log(image.size);
    reader.onload = function(file) {
      var img = new Image();
      console.log(file);
      img.src = file.target.result;
      $('#target').html(img);
    }
    reader.readAsDataURL(image);
    console.log(files);
  });
});</script>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/persons/edit.html.erb
<h1>Edit person</h1>
 
<%= form_with(model: @person) do |form| %>
 
  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@person.errors.count, "error") %> prohibited
        this person from being saved:
      </h2>
      <ul>
        <% @person.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= form.label :Name %><br>
    <%= form.text_field :Name %>
  </p>
 
  <p>
    <%= form.label :Age %><br>
    <%= form.text_area :Age %>
  </p>

 <p>
    <%= form.label :Gender %><br>
Male: <%= form.radio_button :Gender, 'Male' %>
Female:<%= form.radio_button :Gender, 'Female' %>
 <p>
    <%= form.label :Email %><br>
    <%= form.text_area :Email %>
  </p>


  <p>
    <%= form.label :Address %><br>
    <%= form.text_area :Address %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
 
<% end %>
 
<%= link_to 'Back', persons_path %>

app/views/persons/index.html.erb
<h1>Listing Persons</h1>
 
<table>
  <tr>
    <th>Name</th>
    <th>Age</th>
    <th>Gender</th>
    <th>Email</th>
    <th>Address</th>
    <th colspan="2"></th>
  </tr>
 
  <% @persons.each do |person| %>
    <tr>
      <td><%= person.Name %></td>
      <td><%= person.Age %></td>
      <td><%= person.Gender %></td>
      <td><%= person.Email %></td>
      <td><%= person.Address %></td>
      <td><%= link_to 'Show', person_path(person) %></td>
      <td><%= link_to 'Edit', edit_person_path(person) %></td>
      <td><%= link_to 'Destroy', person_path(person),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/persons/new.html.erb
 <%= form_with scope: :person, url: persons_path, local: true do |form| %>
 
  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@person.errors.count, "error") %> prohibited
        this person from being saved:
      </h2>
      <ul>
        <% @person.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= form.label :Name %><br>
    <%= form.text_field :Name %>
  </p>
 
 <p>
    <%= form.label :Age %><br>
    <%= form.text_field :Age %>
  </p>

   <p>
    <%= form.label :Gender %><br>
  <%= form.select :Gender, [['Male','Male'],['Female','Female'],['Other','Other']] %>

  <p>
    <%= form.label :Email %><br>
    <%= form.text_field :Email%>
  </p>
 
<p>
    <%= form.label :Address %><br>
    <%= form.text_area :Address%>
  </p>

  <p>
    <%= form.submit %>
  </p>
 
<% end %>
 
<%= link_to 'Back', persons_path %>

app/views/persons/show.html.erb
<% content_for :head do %>
  <title>A simple page</title>
<% end %>
<p>
  <strong>Name:</strong>
  <%= @person.Name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @person.Age %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @person.Gender %>
</p>
 
<p>
  <strong>Email:</strong>
  <%= @person.Email %>
</p>

<p>
  <strong>Address:</strong>
  <%= @person.Address %>
</p>

<h2>Books</h2>
<% @person.books.each do |book| %>
  <p>
    <strong>Name:</strong>
    <%= book.name %>
  </p>
 
  <p>
    <strong>Pages:</strong>
    <%= book.pages %>
  </p>

  <p>
    <strong>Image:</strong>
<%= link_to image_tag(book.image.url, class: 'media-object'), book.image.url, target: '_blank' %>
      <!-- Button to delete image -->  </p>
  <p>
  <%= link_to 'Destroy Book', [book.person, book],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>
<% end %>

<h2>Add a Book:</h2>
<%= form_with(model: [ @person, @person.books.build ], local: true) do |form| %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>
  <p>
    <%= form.label :pages %><br>
    <%= form.text_field :pages %>
  </p>
  <p id="pictureInput">
    <%= form.label :image %><br>
    <%= form.file_field :image %>  </p>
 <div id="target" >
  </div>
  <p >
    <%= form.submit %>
  </p>
<% end %>

<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', persons_path %>